<?php

/**
 * @file
 * Contains userprofiles.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Controller\ControllerBase;
use Drupal\Core\Entity\EntityInterface;
use Drupal\node\Entity\Node;
use Drupal\Core\Entity;
use Drupal\user\Entity\User;
use Drupal\userprofiles\Entity\PrivateProfile;
use Drupal\userprofiles\Entity\PublicProfile;

/**
 * Implements hook_help().
 */
function userprofiles_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the userprofiles module.
    case 'help.page.userprofiles':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_cron().
 */
function userprofiles_cron() {
	\Drupal::logger('userprofiles-cron')->error('Running');
	//load the user list and check last
	$users = User::loadMultiple();
	$uids = array_keys($users);
	$ulastID = end($uids);
	//load the privates and check last
	$privates = PrivateProfile::loadMultiple();
	$ppids = array_keys($privates);
	$plastID = end($ppids);

	foreach ($ppids as $pid) {
		if(!(in_array($pid, $uids))) {
			$priv = PrivateProfile::load($pid);
			$publ = PublicProfile::load($pid);
			$priv->delete();
			$publ->delete();
		}
	}
}